### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by raspberryananas** [JosephMagiya/Weather-Data-and-Forecasts-from-Open-Weather-API#1]
`
{'cod': 401, 'message': 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'}`

Any ideas?

**Comment by jm-0101** [comment]
Oh yes, you need to go and create your own API key. Once you create and verify your account, an API key will be sent to your email.

For more info - check out the blog I wrote about it on https://towardsdatascience.com/weather-data-and-forecasts-from-open-weather-api-1636691d5ba
